/* Generated By:JavaCC: Do not edit this line. Parser2Constants.java */
package parsersystem;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Parser2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NEW_LINE = 4;
  /** RegularExpression Id. */
  int TAB = 5;
  /** RegularExpression Id. */
  int STRING = 6;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int comentario_final = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"//\"",
    "\"\\n\"",
    "<token of kind 3>",
    "<NEW_LINE>",
    "<TAB>",
    "<STRING>",
  };

}
